### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/coding-swamp-#1]
## 📄 Description
회원가입 방식은 직접 회원가입과 sns로그인 방식이 있습니다.
sns는 깃허브를 우선으로 적용합니다.
회원가입시 받는 정보는 다음과 같습니다.
1. 이미지 (등록안하면 기본 이미지 설정)
2. Username(닉네임)
3. 이메일(아이디) 
4. 비밀번호

## 📄 Todo 
* [x] 회원가입 페이지 UI구현하기
* [x] 아이디/비밀번호 정규식 사용해서 Validation함수 만들기
* [x] 이미지 업로드 기능 구현하기
```
^(?=.[A-Za-z])(?=.\d)(?=.[$@$!%#?&])[A-Za-z\d$@$!%*#?&]{8,}$
```
* [x] 회원정보 API 통신 기능 구현 with axios
* [x] 회원가입 API http 코드에 따른 응답 처리
* [x] 이메일 인증 구현하기

## 📄 ETC
기타사항을 작성합니다.

**Comment by SJ0826** [comment]
로그인 기능구현 완료
