### ISSUE TITLE
[FEATURE] 스터디 유저별 현황 조회

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/coding-swamp-#14]
## 📄 Description

설정 페이지에서 스터디 현황을 조회하고 탈퇴할 수 있습니다.

## 📄 Todo

- [x] 설정페이지에서 참가중인 스터디 리스트를 렌더링 합니다.
- [x] 참가중인 스터디를 누르면 상세 페이지로 이동합니다.
- [x] 탈퇴는 설정페이지에서 할 수 있습니다.
- [x] 설정페이지에서 참가신청한 스터디 리스트를 렌더링 합니다.
