### ISSUE TITLE
[FEATURE] 스터디 관리 기능

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/coding-swamp-#18]
## 📄 Description

스터디 상세 페이지에서 설정 탭에 해당하는 기능입니다.

## 📄 Todo

- [x] 스터디 이름과 설명을 수정할 수 있습니다.
- [x] 스터디장이 스터디 참가 신청 허가를 할 수 있습니다.
- [x] 스터디장이 회원을 강제 탈퇴할 수 있습니다.
- [x] 스터디장이 스터디를 삭제할 수 있습니다.
- [x] 설정 페이지에서 스터디 신청을 취소합니다.
- [x] 설정 페이지에서 스터디 탈퇴를 할 수 있습니다.
