### ISSUE TITLE
메인페이지

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/coding-swamp-#3]
## 📄 Description
서비스에 접속시 가장 먼저 보여지는 페이지입니다.

## 📄 Todo 
* [x] jwt토큰을 디코딩해 받아온 memberId로 받아온 정보를 store에 저장합니다.
* [x] 생성된 스터디목록을 페이지네이션 기능을 이용해 한페이지 당 8개씩 보여줍니다.
* [x] 모각코 / 스터디 기준으로 필터링 기능이 있습니다.
* [x] 스터디 아이템을 클릭하면 모달창에서 스터디 상세정보를 보여줍니다.
* [x] 모달창에서 스터디 신청을 할 수 있습니다.

## 📄 ETC
기타사항을 작성합니다.
