### ISSUE TITLE
스터디 생성 기능

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/coding-swamp-#4]
## 📄 Description
새로운 스터디를 생성할 때 보여지는 페이지입니다.

## 📄 Todo 
* [x] 헤더에 사용자 아이콘을 클릭하면 보여지는 메뉴에 스터디 생성버튼이 있습니다.
* [x] 스터디 생성시 받는 정보는 제목, 설명, 스터디 타입, 썸네일 색상코드, 스터디 시작일 , 스터디 종료일, 스터디 최대인원, 검색시 활용될 태그 입니다.
* [x] 스터디를 생성하면 자동으로 스터디 상세 페이지로 페이지 이동됩니다.

## 📄 ETC
기타사항을 작성합니다.

**Comment by SJ0826** [comment]
스터디 생성 기능 구현

**Comment by SJ0826** [comment]
스터디 생성 기능 구현
